### PR TITLE
Tc issue 99

### PR DESCRIPTION
**Pull request by vsperez**
This adds the cancel feature over the GTFSFileProcess changes.

### CODE REVIEW

**Comment by scrudden** [comment]
Hi Vicente,

I am not sure about using blockid as the parameter to the cancelTrip method of CommandsServer. I think it would be better to pass the tripid and then have it find the correct vehicle on the server side of the interface.

It also seems to be for cancelling "dummy" (SchedBasedVehicle) vehicles only. Is this correct? Could this be changed to also cancel "real" vehicles?

Cheers,

Sean.

**Comment by vsperez** [comment]
Hi Sean,

Let me explain  the logic behind, and please let me know the horrors ;)

The first step is that the trip was never assigned, so schedBasedVehicle is needed. As far as I read, if a vehicle updates the assignment to one trip assigned to “schedBasedVehicle", it will be overrided (the real vehicle will have the assignment). In this case it will have cancel property set  to false.

I didn’t  find a fast way to get the vehicle with the tripI in order to cancel it (that was my first idea). If you remember a way, please let me know.

I belive it could be done with real vehicles.


Best regards
Vicente

**Comment by scrudden** [comment]
Hi Vicente,

In this recent change you asked in a comment "Is it possible to have more than 1 bus with the same tripId??"

For frequency based services this is possible. The unique id in this case is tripid+start_time. So maybe we should have this take these two parameters and if the start_time is null then cancel all vehicles with trip id (will only be one vehicle if scheduled based) and if not null only cancel trip with same tripid and start_time.

Cheers,

Sean.

**Comment by vsperez** [comment]
Hi Sean

After a small issue with git, I finally could commit the last changes.

I add cancel trip relationship for vehicle position feed, to make it consistent with trip updates feed. 

I have a question regarding noSchedule in order to get frequency based trips. In the trip class is this:

` 
                 //Since this constructor is only for frequency based trips where
		// exact_times is true set the corresponding members to indicate such
		this.noSchedule = false;
`


so, is it ok this.noSchedule = false in this case?

Regards
Vicente

**Comment by scrudden** [comment]
Hi Vicente,

They are two constructors in trip for frequency based services. One setting this to true and the other setting it to false. 

The one setting it to false if for when exact_times=1 in the frequencies.txt file which means there is a schedule for stops.

The one setting it to true is for when exact_times=0 in the frequencies.txt file which means it is a "real" frequency based service, with no predetermined schedule for stops.

So, I think it is OK.

Cheers,

Sean.

**Pull request merged**
