### PR TITLE
Tc issue 98

### PR DESCRIPTION
**Pull request by vsperez**
Adds synoptic view over GTFSFileProcess and trip canceling

### CODE REVIEW

**Comment by vsperez** [comment]
Hi,

I add the synoptic view. 

During the implementation, I realized about one thing I did not see, so  I have a question.

What happens with the stop distance over the shape when there is more than one trip pattern?. I have seen something like minor property. The vehicle information is easy, you can get the projection over the route according to the shape associated, but on the stops I did not see that.

It is still pending to deal with canceled trips.

There is an small issue regarding the stop paths distances, the sum of all are greater than the shape length.

**Comment by vsperez** [comment]
Hi Sean,

I was thinking to add headway information to the vehicle tooltip or lable. How can I get that information?. What do you think is better: to read it periodically or by demand?

Best regards
Vicente

**Comment by scrudden** [comment]
@vsperez Am I correct to presume there are no breaking changes in this pull request. By that I mean, there are no changes that will break the predictions. It only effects reporting.

**Comment by vsperez** [comment]
Hi Sean,

As far as I can tell, there are no changes that might affect prediction or other parts of the core processing. All changes are in ipc objects, api objects and Web interface. If you find a change in the core (except for the if obj ==null in the headway generator), please let me know.

**Comment by vsperez** [comment]
This is a screen shot of the new view
screen shot 2018-09-04 at 09 55 22

**Pull request merged**
