### PR TITLE
Add swagger 3 support. 

### PR DESCRIPTION
**Pull request by vsperez**
It was necessary to upgrade the version of jersey. It was added doc.html (swagger ui with theTransitClock icon).
OpenApi.json can be accessed in "api/doc" path.

### CODE REVIEW

**Comment by scrudden** [comment]
How do you access the swagger file?

**Comment by vsperez** [comment]
Hi Sean,

There is an html file. doc.html. So it should be something like:
http://localhost:8080/api/doc.html.

Best regards,
Vicente

**Comment by scrudden** [comment]
Is this html file generated?

**Comment by vsperez** [comment]
Hi Sean,

It is an implementation of swagger UI. It retrieves the Json generated by
swagger-Jersey, and generates the information.
Regards
Vicente

**Comment by scrudden** [comment]
@vsperez Have you done all changes you expect to make? If so, I will merge.

**Comment by vsperez** [comment]
No…I think today I will have it done.

**Comment by scrudden** [comment]
I am getting this screen when I go to http://localhost:8080/api/doc.html

image

**Comment by scrudden** [comment]
@vsperez Do you know why I would be seeing this screen?

**Comment by vsperez** [comment]
Hi Sean,

Yes. I know the reason why. It is my mistake... The file doc.html has the
configuration of the ui. This has the Json URL. It says "
http://localhost:8081/api/doc/openapi.json" . It should be relative link.
"doc/openapi.json".

I will commit the change.

Best regards
Vicente

El 13-07-2018 12:07, "Sean Óg Crudden" <notifications@github.com> escribió:

@vsperez <https://github.com/vsperez> Do you know why I would be seeing
this screen?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TheTransitClock/transitime/pull/72#issuecomment-404878724>,
or mute the thread

**Pull request merged**
