### PR TITLE
resetVehicleView

### PR DESCRIPTION
**Pull request by changtung**
Added view for resetVehicle in xml and json. The vehicle id is in input so user must know vehicleId. Api returned success when i tested it. Please make sure it works correctly.

### CODE REVIEW

**Comment by scrudden** [comment]
Can you add a link to this on the web/reports/apiCalls/index.jsp page. I will try it out then.

**Comment by changtung** [comment]
Added link in ApiCalls since it is Api Call. Is there need to add it in reports and web?

**Comment by scrudden** [comment]
No need to add to reports or web, I think it is good under ApiCalls.

**Comment by scrudden** [comment]
Could we add a UI test for this in [transitimeWebappRegression](https://github.com/TheTransitClock/transitimeWebappRegression)?

**Pull request merged**
