### PR TITLE
Update pom.xml files

### PR DESCRIPTION
**Pull request by nselikoff**
* add logback log appender for AWS CloudWatch
* update target to 1.8
* add tomcat7-maven-plugin

### CODE REVIEW

**Comment by scrudden** [comment]
The travis build failed for this pull request. Tried locally to see if repeats but it does not. This is a bit odd. I am using 

```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

but in the travis file has

```
language: java
jdk: oraclejdk8
```

Not sure if this is the issue.

**Comment by scrudden** [comment]
We could try 

```
jdk: openjdk8 
```

or fix the error being generated

```
[ERROR] /home/travis/build/TheTransitClock/transitime/transitclockWebapp/src/main/java/org/transitclock/reports/ScheduleAdherenceController.java:[118,103] error: incompatible types: bad type in conditional expression
[ERROR]     Integer cannot be converted to Double
[ERROR] /home/travis/build/TheTransitClock/transitime/transitclockWebapp/src/main/java/org/transitclock/reports/ScheduleAdherenceController.java:[119,100] error: incompatible types: bad type in conditional expression
```

**Comment by nselikoff** [comment]
My vote would be to update the travis config to use `openjdk8` - just pushed that. I haven't dealt directly with travis before, so I'm not sure if that's all that is needed... let's see what happens with the travis build...

**Comment by nselikoff** [comment]
...no such luck, same error. I'll submit a separate PR to fix the error in ScheduleAdherenceController.

**Comment by nselikoff** [comment]
https://github.com/TheTransitClock/transitime/pull/90 should allow moving forward with this PR

**Comment by scrudden** [comment]
Built successfully on travis so going to merge.

Might add a jdk.version property to the parent pom file and use it in all others to set the java version. I will do this separately.

**Pull request merged**
