### PR TITLE
Add parameters to improve GTFS File processing.

### PR DESCRIPTION
**Pull request by vsperez**
- maxDistanceBetweenStops: Maximum distance that is expected to have
between two consecutive stops. Default 6000m.
- disableSpecialLoopBackToBeginningCase: Disable that special case. Default false.

### CODE REVIEW

**Comment by vsperez** [comment]
Hi,

I add two parameters, but in one: distanceBetweenStops, I am not quite sure about the default value. In this very moment is 6000m, but I believe it might be too much for all cases. What value do you think is better?

Best regards
Vicente

**Comment by scrudden** [comment]
Hi Vicente,

As I understand it, this pull request is to help with issue #96.

Could you explain how this change (each new config value) helps this issue?

Thanks,

Sean.

**Comment by vsperez** [comment]
Hi Sean,

I found a problem regarding the best match distance along the trip pattern. This occurs when the distance between stops is higher than a certain number (3*times the distance between the current stop and the previous one +600). This is because the process stops searching after than distance over the trip pattern, therefore the correct match is never found. In my case, the best match was at more than 400 m to the shape. In order to avoid that, I just simply add the parameter maxDistanceBetweenStops. If this parameter is greater or equal than 600 it will override the previous condition. 


On the other hand, there is an special case at the beginning of the route. It is much less  important difference than the previous one. This might introduce an error of about 50m in the location of the first stop. So, if the shapes don't loop back to the first stop, it would be good idea to disable it. I add the parameter disableSpecialLoopBackToBeginningCase.

One thing that still haunts me, even though is not really important for predictions, is 128m of difference at the las bus stop position.

**Comment by vsperez** [comment]
The improvement is visible in the map.

screen shot 2018-06-05 at 14 33 16

screen shot 2018-08-18 at 10 38 57

Regards
Vicente

**Pull request merged**
